package com.company;

import java.sql.Timestamp;
import java.util.Arrays;

public class Orders {



    private String timestamp;
    private double totalPrice;
    private String customerName;
    private Pizza[] chosenPizzas;
    private String orderId;

    public static String timeStamp(){
        return "Timestamp: " + new Timestamp(new java.util.Date().getTime());
    }

    @Override
    public String toString() {
        return "Orders{ timeOfOrder: " + timeStamp() +
                " totalPrice=" + totalPrice +
                ", customerName='" + customerName + '\'' +
                ", chosenPizzas=" + Arrays.toString(chosenPizzas) +
                ", orderId='" + orderId + '\'' +
                '}';
    }

    public Orders(String timestamp, double totalPrice, String customerName, Pizza[] chosenPizzas, String orderId) {
        this.timestamp = timestamp;
        this.totalPrice = totalPrice;
        this.customerName = customerName;
        this.chosenPizzas = chosenPizzas;
        this.orderId = orderId;

        //TODO Generate order name (not in order class, method or smth) eks. johnson1234 + johnson1235
        // autogenerated, så vi kan referere tilbage til ordrene når mario vil lave statestik

        //setOrderinactive


    }
    public void showActiveOrders(){


    }
    public void showAllOrders(){

    }
    public void placeOrder(){

    }
}
